<a href="https://colab.research.google.com/github/sdancyger/module1-codexes-claims-analysis/blob/main/analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#ASSIGNMENT

import pandas as pd
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [5]:
#STEP 1 : LOAD THE DATA#

## Replace 'your_file_path.csv' with the actual file path or URL of the dataset

#df = pd.read_csv('https://data.cms.gov/sites/default/files/2023-04/67157de9-d962-4af0-bf0e-3578b3afec58/inpatient.csv')

In [3]:
df = pd.read_csv('https://data.cms.gov/sites/default/files/2023-04/67157de9-d962-4af0-bf0e-3578b3afec58/inpatient.csv')

In [4]:
df

      BENE_ID|CLM_ID|NCH_NEAR_LINE_REC_IDENT_CD|NCH_CLM_TYPE_CD|CLM_FROM_DT|CLM_THRU_DT|NCH_WKLY_PROC_DT|FI_CLM_PROC_DT|CLAIM_QUERY_CODE|PRVDR_NUM|CLM_FAC_TYPE_CD|CLM_SRVC_CLSFCTN_TYPE_CD|CLM_FREQ_CD|FI_NUM|CLM_MDCR_NON_PMT_RSN_CD|CLM_PMT_AMT|NCH_PRMRY_PYR_CLM_PD_AMT|NCH_PRMRY_PYR_CD|FI_CLM_ACTN_CD|PRVDR_STATE_CD|ORG_NPI_NUM|AT_PHYSN_UPIN|AT_PHYSN_NPI|OP_PHYSN_UPIN|OP_PHYSN_NPI|OT_PHYSN_UPIN|OT_PHYSN_NPI|CLM_MCO_PD_SW|PTNT_DSCHRG_STUS_CD|CLM_PPS_IND_CD|CLM_TOT_CHRG_AMT|CLM_ADMSN_DT|CLM_IP_ADMSN_TYPE_CD|CLM_SRC_IP_ADMSN_CD|NCH_PTNT_STATUS_IND_CD|CLM_PASS_THRU_PER_DIEM_AMT|NCH_BENE_IP_DDCTBL_AMT|NCH_BENE_PTA_COINSRNC_LBLTY_AM|NCH_BENE_BLOOD_DDCTBL_LBLTY_AM|NCH_PROFNL_CMPNT_CHRG_AMT|NCH_IP_NCVRD_CHRG_AMT|NCH_IP_TOT_DDCTN_AMT|CLM_TOT_PPS_CPTL_AMT|CLM_PPS_CPTL_FSP_AMT|CLM_PPS_CPTL_OUTLIER_AMT|CLM_PPS_CPTL_DSPRPRTNT_SHR_AMT|CLM_PPS_CPTL_IME_AMT|CLM_PPS_CPTL_EXCPTN_AMT|CLM_PPS_OLD_CPTL_HLD_HRMLS_AMT|CLM_PPS_CPTL_DRG_WT_NUM|CLM_UTLZTN_DAY_CNT|BENE_TOT_COINSRNC_DAYS_CNT|BENE_LRD_USED_CNT|CLM_NON_UTLZTN_DAYS_CNT|NCH_BLOOD_PNTS_FRNSHD_QTY|NCH_VRFD_NCVRD_STAY_FROM_DT|NCH_VRFD_NCVRD_STAY_THRU_DT|NCH_ACTV_OR_CVRD_LVL_CARE_THRU|NCH_BENE_MDCR_BNFTS_EXHTD_DT_I|NCH_BENE_DSCHRG_DT|CLM_DRG_CD|CLM_DRG_OUTLIER_STAY_CD|NCH_DRG_OUTLIER_APRVD_PMT_AMT|ADMTG_DGNS_CD|PRNCPAL_DGNS_CD|ICD_DGNS_CD1|CLM_POA_IND_SW1|ICD_DGNS_CD2|CLM_POA_IND_SW2|ICD_DGNS_CD3|CLM_POA_IND_SW3|ICD_DGNS_CD4|CLM_POA_IND_SW4|ICD_DGNS_CD5|CLM_POA_IND_SW5|ICD_DGNS_CD6|CLM_POA_IND_SW6|ICD_DGNS_CD7|CLM_POA_IND_SW7|ICD_DGNS_CD8|CLM_POA_IND_SW8|ICD_DGNS_CD9|CLM_POA_IND_SW9|ICD_DGNS_CD10|CLM_POA_IND_SW10|ICD_DGNS_CD11|CLM_POA_IND_SW11|ICD_DGNS_CD12|CLM_POA_IND_SW12|ICD_DGNS_CD13|CLM_POA_IND_SW13|ICD_DGNS_CD14|CLM_POA_IND_SW14|ICD_DGNS_CD15|CLM_POA_IND_SW15|ICD_DGNS_CD16|CLM_POA_IND_SW16|ICD_DGNS_CD17|CLM_POA_IND_SW17|ICD_DGNS_CD18|CLM_POA_IND_SW18|ICD_DGNS_CD19|CLM_POA_IND_SW19|ICD_DGNS_CD20|CLM_POA_IND_SW20|ICD_DGNS_CD21|CLM_POA_IND_SW21|ICD_DGNS_CD22|CLM_POA_IND_SW22|ICD_DGNS_CD23|CLM_POA_IND_SW23|ICD_DGNS_CD24|CLM_POA_IND_SW24|ICD_DGNS_CD25|CLM_POA_IND_SW25|FST_DGNS_E_CD|ICD_DGNS_E_CD1|CLM_E_POA_IND_SW1|ICD_DGNS_E_CD2|CLM_E_POA_IND_SW2|ICD_DGNS_E_CD3|CLM_E_POA_IND_SW3|ICD_DGNS_E_CD4|CLM_E_POA_IND_SW4|ICD_DGNS_E_CD5|CLM_E_POA_IND_SW5|ICD_DGNS_E_CD6|CLM_E_POA_IND_SW6|ICD_DGNS_E_CD7|CLM_E_POA_IND_SW7|ICD_DGNS_E_CD8|CLM_E_POA_IND_SW8|ICD_DGNS_E_CD9|CLM_E_POA_IND_SW9|ICD_DGNS_E_CD10|CLM_E_POA_IND_SW10|ICD_DGNS_E_CD11|CLM_E_POA_IND_SW11|ICD_DGNS_E_CD12|CLM_E_POA_IND_SW12|ICD_PRCDR_CD1|PRCDR_DT1|ICD_PRCDR_CD2|PRCDR_DT2|ICD_PRCDR_CD3|PRCDR_DT3|ICD_PRCDR_CD4|PRCDR_DT4|ICD_PRCDR_CD5|PRCDR_DT5|ICD_PRCDR_CD6|PRCDR_DT6|ICD_PRCDR_CD7|PRCDR_DT7|ICD_PRCDR_CD8|PRCDR_DT8|ICD_PRCDR_CD9|PRCDR_DT9|ICD_PRCDR_CD10|PRCDR_DT10|ICD_PRCDR_CD11|PRCDR_DT11|ICD_PRCDR_CD12|PRCDR_DT12|ICD_PRCDR_CD13|PRCDR_DT13|ICD_PRCDR_CD14|PRCDR_DT14|ICD_PRCDR_CD15|PRCDR_DT15|ICD_PRCDR_CD16|PRCDR_DT16|ICD_PRCDR_CD17|PRCDR_DT17|ICD_PRCDR_CD18|PRCDR_DT18|ICD_PRCDR_CD19|PRCDR_DT19|ICD_PRCDR_CD20|PRCDR_DT20|ICD_PRCDR_CD21|PRCDR_DT21|ICD_PRCDR_CD22|PRCDR_DT22|ICD_PRCDR_CD23|PRCDR_DT23|ICD_PRCDR_CD24|PRCDR_DT24|ICD_PRCDR_CD25|PRCDR_DT25|IME_OP_CLM_VAL_AMT|DSH_OP_CLM_VAL_AMT|CLM_UNCOMPD_CARE_PMT_AMT|CLM_LINE_NUM|REV_CNTR|HCPCS_CD|REV_CNTR_DDCTBL_COINSRNC_CD
0      -10000010254618|-10000930037831|V|60|25-Mar-20...
1      -10000010254653|-10000930038030|V|60|24-Sep-20...
2      -10000010254653|-10000930038031|V|60|09-May-20...
3      -10000010254656|-10000930038162|V|60|14-Jan-20...
4      -10000010254656|-10000930038162|V|60|14-Jan-20...
...                                                  ...
58061  -10000010288008|-10000931485965|V|60|08-Jan-20...
58062  -10000010288008|-10000931485967|V|60|23-Oct-20...
58063  -10000010288008|-10000931485969|V|60|22-Aug-20...
58064  -10000010288008|-10000931485971|V|60|13-Sep-20...
58065  -10000010288010|-10000931486024|V|60|11-Jun-20...

[58066 rows x 1 columns]

In [6]:

## Use a delimiter argument if the data is separated by a character other than a comma (e.g., | or ;)
## Use a delimiter argument if the data is separated by a character other than a comma (e.g., | or ;)
## For us we need to use | as the delimiter


data = pd.read_csv('your_file_path.csv', sep='|')
df = pd.read_csv(
    'https://data.cms.gov/sites/default/files/2023-04/67157de9-d962-4af0-bf0e-3578b3afec58/inpatient.csv',
    sep= '|')

<ipython-input-6-8e73d7d0f879>:3: DtypeWarning: Columns (168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [7]:
df

,BENE_ID,CLM_ID,NCH_NEAR_LINE_REC_IDENT_CD,NCH_CLM_TYPE_CD,CLM_FROM_DT,CLM_THRU_DT,NCH_WKLY_PROC_DT,FI_CLM_PROC_DT,CLAIM_QUERY_CODE,PRVDR_NUM,...,PRCDR_DT24,ICD_PRCDR_CD25,PRCDR_DT25,IME_OP_CLM_VAL_AMT,DSH_OP_CLM_VAL_AMT,CLM_UNCOMPD_CARE_PMT_AMT,CLM_LINE_NUM,REV_CNTR,HCPCS_CD,REV_CNTR_DDCTBL_COINSRNC_CD
0,-10000010254618,-10000930037831,V,60,25-Mar-2015,25-Mar-2015,27-Mar-2015,NaN,3,011500,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
1,-10000010254653,-10000930038030,V,60,24-Sep-2015,24-Sep-2015,25-Sep-2015,NaN,3,017129,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
2,-10000010254653,-10000930038031,V,60,09-May-2017,10-May-2017,12-May-2017,NaN,3,010052,...,NaN,NaN,NaN,0,0,NaN,1,1,99024,3.0
3,-10000010254656,-10000930038162,V,60,14-Jan-2017,14-Jan-2017,20-Jan-2017,NaN,3,015455,...,NaN,NaN,NaN,0,0,NaN,1,450,73610,3.0
4,-10000010254656,-10000930038162,V,60,14-Jan-2017,14-Jan-2017,20-Jan-2017,NaN,3,015455,...,NaN,NaN,NaN,0,0,NaN,2,450,29515,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58061,-10000010288008,-10000931485965,V,60,08-Jan-2020,14-Jan-2020,17-Jan-2020,NaN,3,050243,...,NaN,NaN,NaN,0,0,NaN,1,1,99221,NaN
58062,-10000010288008,-10000931485967,V,60,23-Oct-2020,23-Oct-2020,30-Oct-2020,NaN,3,056428,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
58063,-10000010288008,-10000931485969,V,60,22-Aug-2021,23-Aug-2021,27-Aug-2021,NaN,3,056428,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN
58064,-10000010288008,-10000931485971,V,60,13-Sep-2021,16-Sep-2021,17-Sep-2021,NaN,3,050243,...,NaN,NaN,NaN,0,0,NaN,1,1,99221,NaN
58065,-10000010288010,-10000931486024,V,60,11-Jun-2017,11-Jun-2017,16-Jun-2017,NaN,3,555851,...,NaN,NaN,NaN,0,0,NaN,1,450,99221,NaN

In [10]:
## Display the first few rows of the dataset to understand its structure
#print(data.head())

print(df.head)

<bound method NDFrame.head of               BENE_ID          CLM_ID NCH_NEAR_LINE_REC_IDENT_CD  \
0     -10000010254618 -10000930037831                          V
1     -10000010254653 -10000930038030                          V
2     -10000010254653 -10000930038031                          V
3     -10000010254656 -10000930038162                          V
4     -10000010254656 -10000930038162                          V
...               ...             ...                        ...
58061 -10000010288008 -10000931485965                          V
58062 -10000010288008 -10000931485967                          V
58063 -10000010288008 -10000931485969                          V
58064 -10000010288008 -10000931485971                          V
58065 -10000010288010 -10000931486024                          V

       NCH_CLM_TYPE_CD  CLM_FROM_DT  CLM_THRU_DT NCH_WKLY_PROC_DT  \
0                   60  25-Mar-2015  25-Mar-2015      27-Mar-2015
1                   60  24-Sep-2015  24-Sep-2015      25-Sep-2015
2                   60  09-May-2017  10-May-2017      12-May-2017
3                   60  14-Jan-2017  14-Jan-2017      20-Jan-2017
4                   60  14-Jan-2017  14-Jan-2017      20-Jan-2017
...                ...          ...          ...              ...
58061               60  08-Jan-2020  14-Jan-2020      17-Jan-2020
58062               60  23-Oct-2020  23-Oct-2020      30-Oct-2020
58063               60  22-Aug-2021  23-Aug-2021      27-Aug-2021
58064               60  13-Sep-2021  16-Sep-2021      17-Sep-2021
58065               60  11-Jun-2017  11-Jun-2017      16-Jun-2017

       FI_CLM_PROC_DT  CLAIM_QUERY_CODE PRVDR_NUM  ...  PRCDR_DT24  \
0                 NaN                 3    011500  ...         NaN
1                 NaN                 3    017129  ...         NaN
2                 NaN                 3    010052  ...         NaN
3                 NaN                 3    015455  ...         NaN
4                 NaN                 3    015455  ...         NaN
...               ...               ...       ...  ...         ...
58061             NaN                 3    050243  ...         NaN
58062             NaN                 3    056428  ...         NaN
58063             NaN                 3    056428  ...         NaN
58064             NaN                 3    050243  ...         NaN
58065             NaN                 3    555851  ...         NaN

       ICD_PRCDR_CD25  PRCDR_DT25  IME_OP_CLM_VAL_AMT DSH_OP_CLM_VAL_AMT  \
0                 NaN         NaN                   0                  0
1                 NaN         NaN                   0                  0
2                 NaN         NaN                   0                  0
3                 NaN         NaN                   0                  0
4                 NaN         NaN                   0                  0
...               ...         ...                 ...                ...
58061             NaN         NaN                   0                  0
58062             NaN         NaN                   0                  0
58063             NaN         NaN                   0                  0
58064             NaN         NaN                   0                  0
58065             NaN         NaN                   0                  0

       CLM_UNCOMPD_CARE_PMT_AMT  CLM_LINE_NUM REV_CNTR  HCPCS_CD  \
0                           NaN             1      450     99221
1                           NaN             1      450     99221
2                           NaN             1        1     99024
3                           NaN             1      450     73610
4                           NaN             2      450     29515
...                         ...           ...      ...       ...
58061                       NaN             1        1     99221
58062                       NaN             1      450     99221
58063                       NaN             1      450     99221
58064                       NaN             1        1     99221
58065                       NaN             1      450     99221

       REV_CNTR_DDCTBL_COINSRNC_CD
0                              NaN
1                              NaN
2                              3.0
3                              3.0
4                              3.0
...                            ...
58061                          NaN
58062                          NaN
58063                          NaN
58064                          NaN
58065                          NaN

[58066 rows x 197 columns]>

In [11]:
#STEP 2: EXPLORE THE DATA SET#

# Identify the columns related to medical codexes (e.g., ICD codes, DRG codes)

for column in df.columns:
  print(column)

BENE_ID
CLM_ID
NCH_NEAR_LINE_REC_IDENT_CD
NCH_CLM_TYPE_CD
CLM_FROM_DT
CLM_THRU_DT
NCH_WKLY_PROC_DT
FI_CLM_PROC_DT
CLAIM_QUERY_CODE
PRVDR_NUM
CLM_FAC_TYPE_CD
CLM_SRVC_CLSFCTN_TYPE_CD
CLM_FREQ_CD
FI_NUM
CLM_MDCR_NON_PMT_RSN_CD
CLM_PMT_AMT
NCH_PRMRY_PYR_CLM_PD_AMT
NCH_PRMRY_PYR_CD
FI_CLM_ACTN_CD
PRVDR_STATE_CD
ORG_NPI_NUM
AT_PHYSN_UPIN
AT_PHYSN_NPI
OP_PHYSN_UPIN
OP_PHYSN_NPI
OT_PHYSN_UPIN
OT_PHYSN_NPI
CLM_MCO_PD_SW
PTNT_DSCHRG_STUS_CD
CLM_PPS_IND_CD
CLM_TOT_CHRG_AMT
CLM_ADMSN_DT
CLM_IP_ADMSN_TYPE_CD
CLM_SRC_IP_ADMSN_CD
NCH_PTNT_STATUS_IND_CD
CLM_PASS_THRU_PER_DIEM_AMT
NCH_BENE_IP_DDCTBL_AMT
NCH_BENE_PTA_COINSRNC_LBLTY_AM
NCH_BENE_BLOOD_DDCTBL_LBLTY_AM
NCH_PROFNL_CMPNT_CHRG_AMT
NCH_IP_NCVRD_CHRG_AMT
NCH_IP_TOT_DDCTN_AMT
CLM_TOT_PPS_CPTL_AMT
CLM_PPS_CPTL_FSP_AMT
CLM_PPS_CPTL_OUTLIER_AMT
CLM_PPS_CPTL_DSPRPRTNT_SHR_AMT
CLM_PPS_CPTL_IME_AMT
CLM_PPS_CPTL_EXCPTN_AMT
CLM_PPS_OLD_CPTL_HLD_HRMLS_AMT
CLM_PPS_CPTL_DRG_WT_NUM
CLM_UTLZTN_DAY_CNT
BENE_TOT_COINSRNC_DAYS_CNT
BENE_LRD_USED_CNT
CLM_NON_UTLZTN_DAYS_CNT
NCH_BLOOD_PNTS_FRNSHD_QTY
NCH_VRFD_NCVRD_STAY_FROM_DT
NCH_VRFD_NCVRD_STAY_THRU_DT
NCH_ACTV_OR_CVRD_LVL_CARE_THRU
NCH_BENE_MDCR_BNFTS_EXHTD_DT_I
NCH_BENE_DSCHRG_DT
CLM_DRG_CD
CLM_DRG_OUTLIER_STAY_CD
NCH_DRG_OUTLIER_APRVD_PMT_AMT
ADMTG_DGNS_CD
PRNCPAL_DGNS_CD
ICD_DGNS_CD1
CLM_POA_IND_SW1
ICD_DGNS_CD2
CLM_POA_IND_SW2
ICD_DGNS_CD3
CLM_POA_IND_SW3
ICD_DGNS_CD4
CLM_POA_IND_SW4
ICD_DGNS_CD5
CLM_POA_IND_SW5
ICD_DGNS_CD6
CLM_POA_IND_SW6
ICD_DGNS_CD7
CLM_POA_IND_SW7
ICD_DGNS_CD8
CLM_POA_IND_SW8
ICD_DGNS_CD9
CLM_POA_IND_SW9
ICD_DGNS_CD10
CLM_POA_IND_SW10
ICD_DGNS_CD11
CLM_POA_IND_SW11
ICD_DGNS_CD12
CLM_POA_IND_SW12
ICD_DGNS_CD13
CLM_POA_IND_SW13
ICD_DGNS_CD14
CLM_POA_IND_SW14
ICD_DGNS_CD15
CLM_POA_IND_SW15
ICD_DGNS_CD16
CLM_POA_IND_SW16
ICD_DGNS_CD17
CLM_POA_IND_SW17
ICD_DGNS_CD18
CLM_POA_IND_SW18
ICD_DGNS_CD19
CLM_POA_IND_SW19
ICD_DGNS_CD20
CLM_POA_IND_SW20
ICD_DGNS_CD21
CLM_POA_IND_SW21
ICD_DGNS_CD22
CLM_POA_IND_SW22
ICD_DGNS_CD23
CLM_POA_IND_SW23
ICD_DGNS_CD24
CLM_POA_IND_SW24
ICD_DGNS_CD25
CLM_POA_IND_SW25
FST_DGNS_E_CD
ICD_DGNS_E_CD1
CLM_E_POA_IND_SW1
ICD_DGNS_E_CD2
CLM_E_POA_IND_SW2
ICD_DGNS_E_CD3
CLM_E_POA_IND_SW3
ICD_DGNS_E_CD4
CLM_E_POA_IND_SW4
ICD_DGNS_E_CD5
CLM_E_POA_IND_SW5
ICD_DGNS_E_CD6
CLM_E_POA_IND_SW6
ICD_DGNS_E_CD7
CLM_E_POA_IND_SW7
ICD_DGNS_E_CD8
CLM_E_POA_IND_SW8
ICD_DGNS_E_CD9
CLM_E_POA_IND_SW9
ICD_DGNS_E_CD10
CLM_E_POA_IND_SW10
ICD_DGNS_E_CD11
CLM_E_POA_IND_SW11
ICD_DGNS_E_CD12
CLM_E_POA_IND_SW12
ICD_PRCDR_CD1
PRCDR_DT1
ICD_PRCDR_CD2
PRCDR_DT2
ICD_PRCDR_CD3
PRCDR_DT3
ICD_PRCDR_CD4
PRCDR_DT4
ICD_PRCDR_CD5
PRCDR_DT5
ICD_PRCDR_CD6
PRCDR_DT6
ICD_PRCDR_CD7
PRCDR_DT7
ICD_PRCDR_CD8
PRCDR_DT8
ICD_PRCDR_CD9
PRCDR_DT9
ICD_PRCDR_CD10
PRCDR_DT10
ICD_PRCDR_CD11
PRCDR_DT11
ICD_PRCDR_CD12
PRCDR_DT12
ICD_PRCDR_CD13
PRCDR_DT13
ICD_PRCDR_CD14
PRCDR_DT14
ICD_PRCDR_CD15
PRCDR_DT15
ICD_PRCDR_CD16
PRCDR_DT16
ICD_PRCDR_CD17
PRCDR_DT17
ICD_PRCDR_CD18
PRCDR_DT18
ICD_PRCDR_CD19
PRCDR_DT19
ICD_PRCDR_CD20
PRCDR_DT20
ICD_PRCDR_CD21
PRCDR_DT21
ICD_PRCDR_CD22
PRCDR_DT22
ICD_PRCDR_CD23
PRCDR_DT23
ICD_PRCDR_CD24
PRCDR_DT24
ICD_PRCDR_CD25
PRCDR_DT25
IME_OP_CLM_VAL_AMT
DSH_OP_CLM_VAL_AMT
CLM_UNCOMPD_CARE_PMT_AMT
CLM_LINE_NUM
REV_CNTR
HCPCS_CD
REV_CNTR_DDCTBL_COINSRNC_CD

In [ ]:
# Assuming 'ICD_CODE', 'DRG_CODE', and 'HCPCS_CODE' are the columns containing codex data
  #icd_codes = data['ICD_CODE']
  #drg_codes = data['DRG_CODE']
  #hcpcs_codes = data['HCPCS_CODE']

In [18]:
medical_codex_columns = [col for col in df.columns if 'ICD' in col or 'DRG' in col or 'HCPCS' in col]

In [19]:
print(medical_codex_columns)

['CLM_PPS_CPTL_DRG_WT_NUM', 'CLM_DRG_CD', 'CLM_DRG_OUTLIER_STAY_CD', 'NCH_DRG_OUTLIER_APRVD_PMT_AMT', 'ICD_DGNS_CD1', 'ICD_DGNS_CD2', 'ICD_DGNS_CD3', 'ICD_DGNS_CD4', 'ICD_DGNS_CD5', 'ICD_DGNS_CD6', 'ICD_DGNS_CD7', 'ICD_DGNS_CD8', 'ICD_DGNS_CD9', 'ICD_DGNS_CD10', 'ICD_DGNS_CD11', 'ICD_DGNS_CD12', 'ICD_DGNS_CD13', 'ICD_DGNS_CD14', 'ICD_DGNS_CD15', 'ICD_DGNS_CD16', 'ICD_DGNS_CD17', 'ICD_DGNS_CD18', 'ICD_DGNS_CD19', 'ICD_DGNS_CD20', 'ICD_DGNS_CD21', 'ICD_DGNS_CD22', 'ICD_DGNS_CD23', 'ICD_DGNS_CD24', 'ICD_DGNS_CD25', 'ICD_DGNS_E_CD1', 'ICD_DGNS_E_CD2', 'ICD_DGNS_E_CD3', 'ICD_DGNS_E_CD4', 'ICD_DGNS_E_CD5', 'ICD_DGNS_E_CD6', 'ICD_DGNS_E_CD7', 'ICD_DGNS_E_CD8', 'ICD_DGNS_E_CD9', 'ICD_DGNS_E_CD10', 'ICD_DGNS_E_CD11', 'ICD_DGNS_E_CD12', 'ICD_PRCDR_CD1', 'ICD_PRCDR_CD2', 'ICD_PRCDR_CD3', 'ICD_PRCDR_CD4', 'ICD_PRCDR_CD5', 'ICD_PRCDR_CD6', 'ICD_PRCDR_CD7', 'ICD_PRCDR_CD8', 'ICD_PRCDR_CD9', 'ICD_PRCDR_CD10', 'ICD_PRCDR_CD11', 'ICD_PRCDR_CD12', 'ICD_PRCDR_CD13', 'ICD_PRCDR_CD14', 'ICD_PRCDR_CD15', 'ICD_PRCDR_CD16', 'ICD_PRCDR_CD17', 'ICD_PRCDR_CD18', 'ICD_PRCDR_CD19', 'ICD_PRCDR_CD20', 'ICD_PRCDR_CD21', 'ICD_PRCDR_CD22', 'ICD_PRCDR_CD23', 'ICD_PRCDR_CD24', 'ICD_PRCDR_CD25', 'HCPCS_CD']

In [22]:
# ICD
icd_columns = [col for col in medical_codex_columns if 'ICD' in col]
print("\nICD Codex Columns:")
print(icd_columns)

ICD Codex Columns:
['ICD_DGNS_CD1', 'ICD_DGNS_CD2', 'ICD_DGNS_CD3', 'ICD_DGNS_CD4', 'ICD_DGNS_CD5', 'ICD_DGNS_CD6', 'ICD_DGNS_CD7', 'ICD_DGNS_CD8', 'ICD_DGNS_CD9', 'ICD_DGNS_CD10', 'ICD_DGNS_CD11', 'ICD_DGNS_CD12', 'ICD_DGNS_CD13', 'ICD_DGNS_CD14', 'ICD_DGNS_CD15', 'ICD_DGNS_CD16', 'ICD_DGNS_CD17', 'ICD_DGNS_CD18', 'ICD_DGNS_CD19', 'ICD_DGNS_CD20', 'ICD_DGNS_CD21', 'ICD_DGNS_CD22', 'ICD_DGNS_CD23', 'ICD_DGNS_CD24', 'ICD_DGNS_CD25', 'ICD_DGNS_E_CD1', 'ICD_DGNS_E_CD2', 'ICD_DGNS_E_CD3', 'ICD_DGNS_E_CD4', 'ICD_DGNS_E_CD5', 'ICD_DGNS_E_CD6', 'ICD_DGNS_E_CD7', 'ICD_DGNS_E_CD8', 'ICD_DGNS_E_CD9', 'ICD_DGNS_E_CD10', 'ICD_DGNS_E_CD11', 'ICD_DGNS_E_CD12', 'ICD_PRCDR_CD1', 'ICD_PRCDR_CD2', 'ICD_PRCDR_CD3', 'ICD_PRCDR_CD4', 'ICD_PRCDR_CD5', 'ICD_PRCDR_CD6', 'ICD_PRCDR_CD7', 'ICD_PRCDR_CD8', 'ICD_PRCDR_CD9', 'ICD_PRCDR_CD10', 'ICD_PRCDR_CD11', 'ICD_PRCDR_CD12', 'ICD_PRCDR_CD13', 'ICD_PRCDR_CD14', 'ICD_PRCDR_CD15', 'ICD_PRCDR_CD16', 'ICD_PRCDR_CD17', 'ICD_PRCDR_CD18', 'ICD_PRCDR_CD19', 'ICD_PRCDR_CD20', 'ICD_PRCDR_CD21', 'ICD_PRCDR_CD22', 'ICD_PRCDR_CD23', 'ICD_PRCDR_CD24', 'ICD_PRCDR_CD25']

In [29]:
print(icd_columns)

['ICD_DGNS_CD1', 'ICD_DGNS_CD2', 'ICD_DGNS_CD3', 'ICD_DGNS_CD4', 'ICD_DGNS_CD5', 'ICD_DGNS_CD6', 'ICD_DGNS_CD7', 'ICD_DGNS_CD8', 'ICD_DGNS_CD9', 'ICD_DGNS_CD10', 'ICD_DGNS_CD11', 'ICD_DGNS_CD12', 'ICD_DGNS_CD13', 'ICD_DGNS_CD14', 'ICD_DGNS_CD15', 'ICD_DGNS_CD16', 'ICD_DGNS_CD17', 'ICD_DGNS_CD18', 'ICD_DGNS_CD19', 'ICD_DGNS_CD20', 'ICD_DGNS_CD21', 'ICD_DGNS_CD22', 'ICD_DGNS_CD23', 'ICD_DGNS_CD24', 'ICD_DGNS_CD25', 'ICD_DGNS_E_CD1', 'ICD_DGNS_E_CD2', 'ICD_DGNS_E_CD3', 'ICD_DGNS_E_CD4', 'ICD_DGNS_E_CD5', 'ICD_DGNS_E_CD6', 'ICD_DGNS_E_CD7', 'ICD_DGNS_E_CD8', 'ICD_DGNS_E_CD9', 'ICD_DGNS_E_CD10', 'ICD_DGNS_E_CD11', 'ICD_DGNS_E_CD12', 'ICD_PRCDR_CD1', 'ICD_PRCDR_CD2', 'ICD_PRCDR_CD3', 'ICD_PRCDR_CD4', 'ICD_PRCDR_CD5', 'ICD_PRCDR_CD6', 'ICD_PRCDR_CD7', 'ICD_PRCDR_CD8', 'ICD_PRCDR_CD9', 'ICD_PRCDR_CD10', 'ICD_PRCDR_CD11', 'ICD_PRCDR_CD12', 'ICD_PRCDR_CD13', 'ICD_PRCDR_CD14', 'ICD_PRCDR_CD15', 'ICD_PRCDR_CD16', 'ICD_PRCDR_CD17', 'ICD_PRCDR_CD18', 'ICD_PRCDR_CD19', 'ICD_PRCDR_CD20', 'ICD_PRCDR_CD21', 'ICD_PRCDR_CD22', 'ICD_PRCDR_CD23', 'ICD_PRCDR_CD24', 'ICD_PRCDR_CD25']

In [30]:
# DRG
drg_columns = [col for col in df.columns if 'DRG' in col]
print("\nDRG Codex Columns:")
print(drg_columns)

DRG Codex Columns:
['CLM_PPS_CPTL_DRG_WT_NUM', 'CLM_DRG_CD', 'CLM_DRG_OUTLIER_STAY_CD', 'NCH_DRG_OUTLIER_APRVD_PMT_AMT']

In [31]:
# HCPCS
hcpcs_columns = [col for col in df.columns if 'HCPCS' in col]
print("\nHCPCS Codex Columns:")
print(hcpcs_columns)

HCPCS Codex Columns:
['HCPCS_CD']

In [ ]:
# STEP 3: ANALYZE THE FREQUENCY OF EACH UNIQUE VALUE#
## Calculate the frequency of unique values in each codex column

In [34]:
### FREQUENCY COUNT FOR ICD CODES ###

# df.ICD_DGNS_CD1.value_counts()

df.ICD_DGNS_CD1.value_counts()

ICD_DGNS_CD1
Z733      13031
Z608       8227
T7432X     3727
Z604       3537
Z940       2858
          ...
T8611         1
E1141         1
E11610        1
I071          1
M069          1
Name: count, Length: 231, dtype: int64

In [35]:
# df.ICD_DGNS_CD7.value_counts()

df.ICD_DGNS_CD7.value_counts()

ICD_DGNS_CD7
E1121      3205
Z653       3129
R931       2661
N1830      2449
E1129      2230
           ...
Q058          1
R509          1
F02ZFYZ       1
R29898        1
Q6690         1
Name: count, Length: 210, dtype: int64

In [36]:
# df.ICD_DGNS_CD22.value_counts()

df.ICD_DGNS_CD22.value_counts()

ICD_DGNS_CD22
D649      1614
E669      1584
R7303     1532
E781      1086
Z560       923
          ...
R6521        1
E848         1
Z95818       1
S73006       1
P7883        1
Name: count, Length: 116, dtype: int64

In [43]:
# df.ICD_PRCDR_CD3.value_counts()

df.ICD_PRCDR_CD3.value_counts()

ICD_PRCDR_CD3
Z9181      8017
F419       7868
Z1331      6869
Z139       3057
F08H5ZZ    2722
Z9981      2231
F13        2054
BW03ZZZ    2002
M859       1810
Z741       1597
F1990       674
3E033FZ     643
Z715         76
F109         74
Z5189        50
07HN33Z      32
30273R1      27
Z1239        19
6A550Z2      15
Z8616        14
6A551Z2      14
Z000         14
B920ZZZ      13
30243K1      13
I499         12
02RF37H       6
30277R1       6
0FB40ZZ       5
02RF3KZ       4
02RF4KZ       4
02RF3KH       4
02RF38H       4
0FB44ZZ       4
02RF08Z       2
0BP17DZ       2
0BP13DZ       2
02RF3JH       2
0BP1XDZ       2
0BP10DZ       2
02RF47Z       2
02RF37Z       2
02RF3JZ       2
02RF4JZ       2
0HBT3ZX       1
0HBU3ZX       1
0HBV7ZX       1
0HBU0ZZ       1
0HBV0ZZ       1
0HCU3ZZ       1
0HBU7ZZ       1
DF031ZZ       1
0HCT0ZZ       1
0HBV3ZZ       1
Name: count, dtype: int64

In [44]:
# df.ICD_PRCDR_CD7.value_counts()

df.ICD_PRCDR_CD7.value_counts()

ICD_PRCDR_CD7
F1990      4285
Z715       2967
F109       2966
Z9981      2173
Z1331      2005
F08H5ZZ    1657
BW03ZZZ    1148
F13         938
6A550Z2      16
Z8616        14
6A551Z2      12
Name: count, dtype: int64

In [45]:
# df.ICD_PRCDR_CD13.value_counts()

df.ICD_PRCDR_CD13.value_counts()

ICD_PRCDR_CD13
Z9981      1448
F08H5ZZ     727
F13         230
Z8616        38
Name: count, dtype: int64

In [37]:
### FREQUENCY COUNT FOR DRG CODES ###

# df.CLM_DRG_CD.value_counts()

df.CLM_DRG_CD.value_counts()

CLM_DRG_CD
951.0    28831
950.0     1456
949.0     1332
922.0     1110
923.0     1015
         ...
814.0        1
918.0        1
870.0        1
812.0        1
656.0        1
Name: count, Length: 167, dtype: int64

In [38]:
# df.CLM_DRG_OUTLIER_STAY_CD.value_counts()

df.CLM_DRG_OUTLIER_STAY_CD.value_counts()

CLM_DRG_OUTLIER_STAY_CD
0    56137
2     1925
1        4
Name: count, dtype: int64

In [40]:
# df.CLM_PPS_CPTL_DRG_WT_NUM.value_counts()

df.CLM_PPS_CPTL_DRG_WT_NUM.value_counts()

CLM_PPS_CPTL_DRG_WT_NUM
0    58066
Name: count, dtype: int64

In [41]:
### FREQUENCY COUNT FOR HCPCS CODES ###

# df.CHCPCS_CD.value_counts()

df.HCPCS_CD.value_counts()

HCPCS_CD
99221    8298
G0444    7990
96156    5080
99408    4196
99495    3867
         ...
S9361       1
S9355       1
S9374       1
S9377       1
G9829       1
Name: count, Length: 106, dtype: int64

In [ ]:
# STEP 4: HANDLE MISSING DATA (IF ANY)
## Check for missing values in codex-related columns
missing_icd = icd_codes.isnull().sum()
missing_drg = drg_codes.isnull().sum()
missing_hcpcs = hcpcs_codes.isnull().sum()

print(f"Missing ICD Codes: {missing_icd}")
print(f"Missing DRG Codes: {missing_drg}")
print(f"Missing HCPCS Codes: {missing_hcpcs}")

In [55]:
missing_icd_dgns_cd1 = df['ICD_DGNS_CD1'].isnull().sum()

print(f"Missing values in ICD_DGNS_CD1: {missing_icd_dgns_cd1}")

Missing values in ICD_DGNS_CD1: 0

In [56]:
missing_icd_dgns_cd7 = df['ICD_DGNS_CD7'].isnull().sum()

print(f"Missing values in ICD_DGNS_CD7: {missing_icd_dgns_cd7}")

Missing values in ICD_DGNS_CD7: 2282

In [57]:
missing_icd_dgns_cd22 = df['ICD_DGNS_CD22'].isnull().sum()

print(f"Missing values in ICD_DGNS_CD22: {missing_icd_dgns_cd22}")

Missing values in ICD_DGNS_CD22: 39841

In [71]:
missing_icd_prcdr_cd3 = df['ICD_PRCDR_CD3'].isnull().sum()

print(f"Missing values in ICD_PRCDR_CD3: {missing_icd_prcdr_cd3}")

Missing values in ICD_PRCDR_CD3: 18082

In [70]:
missing_icd_prcdr_cd7 = df['ICD_PRCDR_CD7'].isnull().sum()

print(f"Missing values in ICD_PRCDR_CD7: {missing_icd_prcdr_cd7}")

Missing values in ICD_PRCDR_CD7: 39885

In [60]:
missing_icd_prcdr_cd13 = df['ICD_PRCDR_CD13'].isnull().sum()

print(f"Missing values in ICD_PRCDR_CD13: {missing_icd_prcdr_cd13}")

Missing values in ICD_PRCDR_CD13: 55623

In [61]:
missing_drg_cd = df['CLM_DRG_CD'].isnull().sum()

print(f"Missing values in CLM_DRG_CD: {missing_drg_cd}")

Missing values in CLM_DRG_CD: 3262

In [62]:
missing_drg_outlier_cd = df['CLM_DRG_OUTLIER_STAY_CD'].isnull().sum()

print(f"Missing values in CLM_DRG_OUTLIER_STAY_CD: {missing_drg_outlier_cd}")

Missing values in CLM_DRG_OUTLIER_STAY_CD: 0

In [63]:
missing_drg_wt_num = df['CLM_PPS_CPTL_DRG_WT_NUM'].isnull().sum()

print(f"Missing values in CLM_PPS_CPTL_DRG_WT_NUM: {missing_drg_wt_num}")

Missing values in CLM_PPS_CPTL_DRG_WT_NUM: 0

In [64]:
missing_hcpcs_cd = df['HCPCS_CD'].isnull().sum()

print(f"Missing values in HCPCS_CD: {missing_hcpcs_cd}")

Missing values in HCPCS_CD: 0

In [76]:
# Example of handling missing data by filling with a placeholder
df['ICD_DGNS_CD1'].fillna('MISSING', inplace=True)

df['ICD_DGNS_CD7'].fillna('MISSING', inplace=True)

df['ICD_DGNS_CD22'].fillna('MISSING', inplace=True)

df['ICD_PRCDR_CD3'].fillna('MISSING', inplace=True)

df['ICD_PRCDR_CD7'].fillna('MISSING', inplace=True)

df['ICD_PRCDR_CD13'].fillna('MISSING', inplace=True)

df['CLM_DRG_CD'].fillna('MISSING', inplace=True)

df['CLM_DRG_OUTLIER_STAY_CD'].fillna('MISSING', inplace=True)

df['CLM_PPS_CPTL_DRG_WT_NUM'].fillna('MISSING', inplace=True)

df['HCPCS_CD'].fillna('MISSING', inplace=True)

In [ ]:
# STEP 5: SUMMARY OF FINDINGS
## Provide a summary of the most common codes
## Here we'll just print the top 5 most common codes for each category
print("Top 5 Most Common ICD Codes:\n", icd_frequency.head())
print("Top 5 Most Common DRG Codes:\n", drg_frequency.head())
print("Top 5 Most Common HCPCS Codes:\n", hcpcs_frequency.head())

In [80]:
icd_frequency = pd.concat([df[col] for col in icd_columns]).dropna().value_counts()

In [81]:
print("Top 5 Most Common ICD Codes:\n", icd_frequency.head())

Top 5 Most Common ICD Codes:
            638726
MISSING    155713
Z1331       50262
E1121       48502
E669        42659
Name: count, dtype: int64

In [83]:
drg_frequency = pd.concat([df[col] for col in drg_columns]).dropna().value_counts()

In [84]:
print("Top 5 Most Common DRG Codes:\n", drg_frequency.head())

Top 5 Most Common DRG Codes:
 0          114203
951.0       28831
MISSING      3262
2            1925
950.0        1456
Name: count, dtype: int64

In [88]:
hcpcs_column = 'HCPCS_CD'
hcpcs_frequency = df[hcpcs_column].dropna().value_counts()

In [89]:
print("Top 5 Most Common HCPCS Codes:\n", hcpcs_frequency.head())

Top 5 Most Common HCPCS Codes:
 HCPCS_CD
99221    8298
G0444    7990
96156    5080
99408    4196
99495    3867
Name: count, dtype: int64

In [ ]:
# Additional Analysis Example
# Are there any patterns? For instance, let's see if certain DRG codes are more common
# when ICD codes are specific values (e.g., 'E11' for Type 2 Diabetes)
diabetes_related = data[data['ICD_CODE'].str.contains('E11', na=False)]
common_drg_for_diabetes = diabetes_related['DRG_CODE'].value_counts()
print("Most Common DRG Codes for Patients with ICD Code E11 (Type 2 Diabetes):\n", common_drg_for_diabetes)